version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: docker_test/test/Dockerfile
    restart: always
    container_name: patient_test_app
    expose:
      - "9999"
    ports:
      - 9999:9999
    command: run_tests